// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BankSimulation
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TransactionResult : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TransactionResult\",\"namespace\":\"BankSimulation\",\"fields\"" +
				":[{\"name\":\"transactionID\",\"type\":\"string\"},{\"name\":\"result\",\"type\":\"boolean\"}]}");
		private string _transactionID;
		private bool _result;
		public virtual Schema Schema
		{
			get
			{
				return TransactionResult._SCHEMA;
			}
		}
		public string transactionID
		{
			get
			{
				return this._transactionID;
			}
			set
			{
				this._transactionID = value;
			}
		}
		public bool result
		{
			get
			{
				return this._result;
			}
			set
			{
				this._result = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.transactionID;
			case 1: return this.result;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.transactionID = (System.String)fieldValue; break;
			case 1: this.result = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
