// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BankSimulation
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Transaction : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Transaction\",\"namespace\":\"BankSimulation\",\"fields\":[{\"na" +
				"me\":\"transactionID\",\"type\":\"string\"},{\"name\":\"cardNumber\",\"type\":\"string\"},{\"nam" +
				"e\":\"code\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"float\"}]}");
		private string _transactionID;
		private string _cardNumber;
		private string _code;
		private float _amount;
		public virtual Schema Schema
		{
			get
			{
				return Transaction._SCHEMA;
			}
		}
		public string transactionID
		{
			get
			{
				return this._transactionID;
			}
			set
			{
				this._transactionID = value;
			}
		}
		public string cardNumber
		{
			get
			{
				return this._cardNumber;
			}
			set
			{
				this._cardNumber = value;
			}
		}
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				this._code = value;
			}
		}
		public float amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				this._amount = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.transactionID;
			case 1: return this.cardNumber;
			case 2: return this.code;
			case 3: return this.amount;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.transactionID = (System.String)fieldValue; break;
			case 1: this.cardNumber = (System.String)fieldValue; break;
			case 2: this.code = (System.String)fieldValue; break;
			case 3: this.amount = (System.Single)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
